dataset:
  split_source: teethseg22

segmentation_dataset:
  feature_keys:
    - pos
    - normal
  target_key: y_arch_class

dataloader:
  train:
    batch_size: 16
    num_workers: 4
    shuffle: true
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 2
  eval:
    batch_size: 16
    num_workers: 4
    shuffle: false
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 2
